theme: jekyll-theme-cayman
name: Alex Dannemiller's GitHub Portfolio
title: Alex Dannemiller - GitHub Portfolio
description: A sample portfolio of work, including coding projects, designs, and writing.
url: "spacemoss.github.io"
github_username: spacemoss
