theme: jekyll-theme-cayman
name: Alex Dannemiller's Portfolio
description: A collection of projects for Alex's portfolio, including code, graphic design, and editing.
url: "spacemoss.github.io"
github_username: spacemoss
